### ISSUE TITLE
Looping Bugs

### ISSUE THREAD

**Issue by Algorithmus** [libertyernie/rstmcpp#1]
If you try to use the -l flags, one of two things happens:

In main.cpp:

```
while (*ptr >= '0' && *ptr <= '9') {
				// Parse digit
				loopStart = loopStart * 10 + (*ptr - '0');
			}
			if (*ptr == '-') {
				// Get loop end
				loopEnd = 0;
				ptr++;
				while (*ptr >= '0' && *ptr <= '9') {
					// Parse digit
					loopEnd = loopEnd * 10 + (*ptr - '0');
				}
			} else {
				loopEnd = -1;
			}
```
1 If you don't specify the start and end points, `loopEnd = -1` and a value smaller than loopStart is chosen, so the wrong endpoint is set. The program segfaults. Works with `loopEnd = 0`.

2 If you specify a loop start and end point, you get stuck in the while loops because ptr doesn't go anywhere.

**Comment by libertyernie** [comment]
Could you see if it's fixed in this fork?

https://gitlab.com/beelzy/rstmcpp/

If not, if you could send a pull request, it would be appreciated. I don't really maintain this repo anymore (most of my apps are in .NET and I usually rely on VGAudio for encoding).

**Comment by Algorithmus** [comment]
Yes, I fixed those in my fork. Here are the diffs: https://gitlab.com/beelzy/rstmcpp/commit/d58712f9afaa5ab71c44806198622668afd56713
https://gitlab.com/beelzy/rstmcpp/commit/6f397565b9b47e812893f70b82b17660bae1ded6
The line numbers may be different though.

**Comment by libertyernie** [comment]
Cool, thanks! I'll merge it in. (I could merge the CWAV stuff in too if you like.)

**Comment by Algorithmus** [comment]
Sure, go ahead. You are using the cwav stuff for looping audio converter anyways.
