### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Algorithmus** [libertyernie/rstmcpp#2]
@libertyernie
So I forgot to ask about this, and didn't realize the implications, but apparently, rstmcpp has no license so to speak; I didn't think this through when I made my fork on gitlab, so it is unclear what rights I have to use your code in the original rstmcpp.

You didn't complain when I mentioned I extended it to support bcwavs, so I must assume you're not entirely against my fork.

But to be clear about the licensing so that I can use my fork in some Linux distros, I was wondering if it was okay for me to license my fork under MIT or some other permissive license?

**Comment by libertyernie** [comment]
I'd be OK with anything I wrote for rstmcpp being distributed under the MIT or ISC licenses:

    ISC License

    (C) 2016 libertyernie

    Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

The only reason I didn't put a license file in the repo like I usually do is because some of the code was taken from BrawlLib, and BrawlBox doesn't really have a proper license to speak of (and it's had a handful of different contributors over the years.)

**Comment by Algorithmus** [comment]
Okay, thanks. I'll try to make do with that. It's probably fairly difficult at this point to ask all the contributors to  agree to having a license since I imagine some of them aren't around anymore.
